# 05 - Model Training (Forecast Engine)

## Objective
Train and tune a machine learning pipeline that predicts **next-day return** for each StockMetrics ticker.

This trained model is used by the dashboard as a **short-term educational estimate** to demonstrate how difficult short-horizon market prediction can be.

Long-horizon scenario ranges shown in the dashboard are generated separately using **historical trend and volatility**, not by compounding the ML model’s daily predictions.

## Inputs
- Feature dataset: `data/processed/<version>/features_<version>_latest.csv`
- Version label (e.g. `v2`)

## Outputs
- Saved trained pipeline: `models/stock_forecast_model_<version>.pkl`
- Training report (metrics + best params): `outputs/<version>/reports/model_training_report_<version>.json`
- Console summary: train/test metrics and best hyperparameters

## CRISP-DM Stage
Modelling

In [ ]:
# Make the project root importable (so `import src...` works in notebooks)
import sys
from pathlib import Path

import json

import numpy as np
import pandas as pd
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

from src.config import DEFAULT_VERSION, get_paths
from src.features import load_features_latest
from src.modelling import (
    FEATURE_COLS_CAT,
    FEATURE_COLS_NUM,
    TARGET_COL,
    save_model,
    time_split,
    train_and_tune,
)

# notebooks live in jupyter_notebooks/
PROJECT_ROOT = Path("..").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project root added to sys.path:", PROJECT_ROOT)

np.random.seed(42)

Project root added to sys.path: C:\Users\Louis\Documents\vscode-projects\stockmetrics

In [3]:
VERSION = DEFAULT_VERSION
paths = get_paths(VERSION)

MODELS_DIR = paths.models_dir
REPORTS_DIR = paths.outputs_dir / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

print("Version:", VERSION)
print("Models dir:", MODELS_DIR)
print("Reports dir:", REPORTS_DIR)

Version: v2
Models dir: C:\Users\Louis\Documents\vscode-projects\stockmetrics\models
Reports dir: C:\Users\Louis\Documents\vscode-projects\stockmetrics\outputs\v2\reports

In [ ]:
feat_df = load_features_latest(paths.processed_dir, VERSION)

print("Loaded features shape:", feat_df.shape)
print("Tickers:", sorted(feat_df["Ticker"].unique().tolist()))
print(
    "Date range:",
    feat_df["Date"].min().date(),
    "to",
    feat_df["Date"].max().date(),
)

display(feat_df.head(5))
display(feat_df.groupby("Ticker").head(2))

Loaded features shape: (30488, 21)
Tickers: ['AAPL', 'AMZN', 'GOOGL', 'META', 'MSFT', 'NVDA', 'TSLA', 'VUSA.L', 'VWRL.L']
Date range: 2012-09-28 to 2026-03-17

,Date,Open,High,Low,Close,Adj_Close,Volume,Ticker,return_1d,target_next_day_return,...,vol_30d,vol_90d,mom_30d,mom_90d,zscore_30d,mean_reversion_5d,drawdown,lag_return_1,lag_return_5,lag_return_21
0,2012-10-01,34.349998,34.349998,34.349998,34.349998,27.352087,0,VWRL.L,0.012379,-0.006695,...,0.007959,0.008218,-0.000052,0.001067,1.561843,0.012934,-0.013357,-0.001472,-0.004191,0.008492
1,2012-10-02,34.310001,34.470001,34.195999,34.119999,27.168957,136095,VWRL.L,-0.006695,0.007034,...,0.008047,0.008244,-0.000222,0.001033,-0.804488,-0.004133,-0.019962,0.012379,0.003338,-0.000148
2,2012-10-03,34.389999,34.389999,34.389999,34.360001,27.360052,7687,VWRL.L,0.007034,0.000437,...,0.008140,0.008110,-0.000075,0.000932,0.873192,0.004313,-0.013069,-0.006695,-0.019381,-0.012116
3,2012-10-04,34.459999,34.555000,34.438000,34.375000,27.372002,2203,VWRL.L,0.000437,0.006691,...,0.007736,0.008110,0.000390,0.000931,0.006083,-0.001900,-0.012638,0.007034,0.002360,-0.000299
4,2012-10-05,34.525002,34.525002,34.525002,34.605000,27.555138,285,VWRL.L,0.006691,-0.001011,...,0.007820,0.008013,0.000613,0.000850,0.777190,0.002722,-0.006032,0.000437,-0.001472,0.019000

,Date,Open,High,Low,Close,Adj_Close,Volume,Ticker,return_1d,target_next_day_return,...,vol_30d,vol_90d,mom_30d,mom_90d,zscore_30d,mean_reversion_5d,drawdown,lag_return_1,lag_return_5,lag_return_21
0,2012-10-01,34.349998,34.349998,34.349998,34.349998,27.352087,0,VWRL.L,0.012379,-0.006695,...,0.007959,0.008218,-0.000052,0.001067,1.561843,0.012934,-0.013357,-0.001472,-0.004191,0.008492
1,2012-10-02,34.310001,34.470001,34.195999,34.119999,27.168957,136095,VWRL.L,-0.006695,0.007034,...,0.008047,0.008244,-0.000222,0.001033,-0.804488,-0.004133,-0.019962,0.012379,0.003338,-0.000148
3400,2012-10-01,17.020000,17.129999,17.010000,17.110001,14.310986,245276,VUSA.L,0.011229,-0.007013,...,0.006294,0.006651,-0.000136,0.000927,1.805850,0.011769,-0.008116,0.001776,-0.001745,0.002960
3401,2012-10-02,17.010000,17.080000,16.990000,16.990000,14.210617,33483,VUSA.L,-0.007013,0.010006,...,0.006413,0.006696,-0.000312,0.000872,-1.045058,-0.004838,-0.015072,0.011229,0.001166,-0.001771
6800,2012-09-28,24.241072,24.325357,23.812500,23.825001,20.074144,535110800,AAPL,-0.020871,-0.011558,...,0.014546,0.013432,0.001677,0.002144,-1.550076,-0.011416,-0.049851,0.024264,0.001990,-0.001971
6801,2012-10-01,23.969999,24.169643,23.446428,23.549643,19.842133,543594800,AAPL,-0.011558,0.002912,...,0.014382,0.013296,0.000675,0.001744,-0.850574,-0.002448,-0.060832,-0.020871,-0.013284,-0.014254
10184,2012-09-28,12.807000,12.850000,12.660000,12.716000,12.716000,49132000,AMZN,-0.008847,-0.009083,...,0.012201,0.015863,0.001790,0.001973,-0.871826,-0.006500,-0.028126,0.027717,-0.012806,0.004104
10185,2012-10-01,12.770000,12.808000,12.524500,12.600500,12.600500,51624000,AMZN,-0.009083,-0.005595,...,0.012348,0.015888,0.001540,0.001772,-0.860262,-0.006993,-0.036953,-0.008847,-0.010370,-0.003642
13568,2012-09-28,18.872623,19.001501,18.797548,18.881380,18.726606,111228660,GOOGL,-0.002644,0.009649,...,0.010132,0.012295,0.003873,0.002609,-0.643249,-0.008205,-0.002644,0.004035,0.008062,0.015888
13569,2012-10-01,18.995245,19.144144,18.924173,19.063564,18.907297,126593280,GOOGL,0.009649,-0.006288,...,0.010177,0.012253,0.003983,0.002556,0.556670,0.006352,0.000000,-0.002644,0.020968,-0.009200
16952,2012-09-28,20.570000,21.950001,20.500000,21.660000,21.491346,65486000,META,0.065945,0.015235,...,0.038521,0.039132,0.003595,-0.003206,1.618585,0.075329,-0.345619,-0.014549,0.011952,-0.012410
16953,2012-10-01,22.080000,22.590000,21.730000,21.990000,21.818777,51262700,META,0.015235,0.012733,...,0.037623,0.038999,0.005479,-0.003396,0.259325,0.003462,-0.335650,0.065945,-0.090551,-0.000524
20336,2012-09-28,30.180000,30.260000,29.740000,29.760000,23.716797,54229300,MSFT,-0.013263,-0.009072,...,0.010185,0.013379,-0.001073,0.000162,-1.196793,-0.003933,-0.053736,-0.000331,-0.008267,0.000653
20337,2012-10-01,29.809999,29.980000,29.420000,29.490000,23.501627,54042700,MSFT,-0.009072,0.005765,...,0.010242,0.013210,-0.001505,0.000304,-0.738824,-0.000557,-0.062321,-0.013263,-0.013145,-0.010767
23720,2012-09-28,0.330500,0.338250,0.326250,0.333500,0.305748,485508000,NVDA,0.004518,-0.016491,...,0.016608,0.021816,-0.003276,0.001283,0.469270,0.009333,-0.099257,0.007588,0.004408,0.002099
23721,2012-10-01,0.335000,0.337000,0.326750,0.328000,0.300705,504236000,NVDA,-0.016491,0.003811,...,0.016755,0.021751,-0.003533,0.000825,-0.773407,-0.008523,-0.114112,0.004518,-0.000731,-0.018855
27104,2012-09-28,1.915333,1.992667,1.907333,1.952000,1.952000,65151000,TSLA,0.027729,-0.004098,...,0.034325,0.034820,-0.000561,0.000040,0.824189,0.031458,-0.185762,0.034495,-0.028479,-0.009760
27105,2012-10-01,1.966667,1.992667,1.933333,1.944000,1.944000,13266000,TSLA,-0.004098,0.021948,...,0.034290,0.034814,-0.000379,-0.000085,-0.108476,0.004714,-0.189099,0.027729,0.021319,0.000000

In [5]:
required_cols = {"Date", "Ticker", "target_next_day_return"}
missing = required_cols - set(feat_df.columns)
if missing:
    raise KeyError(f"Missing required columns in features dataset: {missing}")

print("Target column present:", "target_next_day_return" in feat_df.columns)
print("Non-null target rows:", feat_df["target_next_day_return"].notna().sum())

Target column present: True
Non-null target rows: 30488

In [ ]:
# Sanity check: daily return scale (should be small numbers, not percentages)
print("\nTarget summary (next-day return):")
display(feat_df["target_next_day_return"].describe())

print("\nLargest absolute daily returns (should be rare but not insane):")
display(
    feat_df["target_next_day_return"]
    .abs()
    .sort_values(ascending=False)
    .head(10)
)

Target summary (next-day return):

count    30488.000000
mean         0.001196
std          0.021605
min         -0.263901
25%         -0.007558
50%          0.000959
75%          0.009920
max          0.298067
Name: target_next_day_return, dtype: float64

Largest absolute daily returns (should be rare but not insane):

24756    0.298067
17155    0.296115
19303    0.263901
19487    0.245571
27254    0.243951
26399    0.243696
19553    0.232824
30252    0.226900
30139    0.219190
29100    0.210628
Name: target_next_day_return, dtype: float64

## ML Business Case (Training Notebook)

### Predictive Task
This project uses **supervised learning (regression)** to predict a ticker’s **next-day return** based on engineered historical features.

### Why this matters for StockMetrics
StockMetrics aims to reduce analysis paralysis for beginner investors by:

- highlighting volatility and risk behaviour,
- presenting outcomes as scenario forecast ranges (optimistic / realistic / pessimistic),
- keeping the focus on a small, curated set of well-known tickers.

The machine learning model is used as a **short-term educational signal** to show how difficult next-day market prediction is in practice.

Long-horizon scenario ranges are generated separately using historical trend and volatility rather than compounding noisy daily ML predictions.

### Success Criteria
- Primary metric: **R²** on a chronological (time-aware) test split.
- Secondary metrics: **MAE** and **RMSE**.

If test-set R² is close to 0 or negative (which is common in financial return prediction),
the model will still be useful for illustrating uncertainty but forecasts must be framed
as probabilistic ranges rather than precise predictions.

In [ ]:
# Basic checks before fitting any models
print("Rows:", len(feat_df))
print("Columns:", len(feat_df.columns))
print("Tickers:", feat_df["Ticker"].nunique())
print("Date min/max:", feat_df["Date"].min(), "->", feat_df["Date"].max())
print(
    "Any NA in target:",
    feat_df["target_next_day_return"].isna().any(),
)

# Small random subset to make sure the training pipeline runs quickly
# (does not modify the saved dataset)
smoke_df = (
    feat_df.sample(3000, random_state=42)
    .sort_values(["Date", "Ticker"])
)
print("Smoke test rows:", len(smoke_df))

Rows: 30488
Columns: 21
Tickers: 9
Date min/max: 2012-09-28 00:00:00 -> 2026-03-17 00:00:00
Any NA in target: False
Smoke test rows: 3000

In [8]:
print("Rows for training (smoke test):", len(smoke_df))

result = train_and_tune(smoke_df, test_size=0.2, fast=True)

print("\nBest Params:")
for k, v in result.best_params.items():
    print(f"- {k}: {v}")

print("\nTrain Metrics:")
for k, v in result.metrics_train.items():
    print(f"- {k}: {v:.6f}")

print("\nTest Metrics:")
for k, v in result.metrics_test.items():
    print(f"- {k}: {v:.6f}")

Rows for training (smoke test): 3000
Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.1s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.0s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.0s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.1s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.1s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.2s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.3s

Best Params:
- model__max_depth: 5
- model__max_features: sqrt
- model__max_leaf_nodes: 200
- model__min_samples_leaf: 1
- model__min_samples_split: 2
- model__n_estimators: 50

Train Metrics:
- r2: 0.185619
- mae: 0.013263
- rmse: 0.019754

Test Metrics:
- r2: -0.032475
- mae: 0.014319
- rmse: 0.021672

In [9]:
# Medium-size test (faster than full dataset, bigger than smoke test)
medium_df = (
    feat_df.sample(10000, random_state=42)
    .sort_values(["Date", "Ticker"])
    .reset_index(drop=True)
)

print("Medium test rows:", len(medium_df))

Medium test rows: 10000

In [10]:
print("Rows for training (medium test):", len(medium_df))

result = train_and_tune(medium_df, test_size=0.2, fast=True)

print("\nBest Params:")
for k, v in result.best_params.items():
    print(f"- {k}: {v}")

print("\nTrain Metrics:")
for k, v in result.metrics_train.items():
    print(f"- {k}: {v:.6f}")

print("\nTest Metrics:")
for k, v in result.metrics_test.items():
    print(f"- {k}: {v:.6f}")

Rows for training (medium test): 10000
Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.3s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.4s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.6s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.1s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.3s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=25; total time=   0.5s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.3s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   0.7s
[CV] END model__max_depth=10, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=50; total time=   1.1s

Best Params:
- model__max_depth: 5
- model__max_features: sqrt
- model__max_leaf_nodes: 200
- model__min_samples_leaf: 1
- model__min_samples_split: 2
- model__n_estimators: 25

Train Metrics:
- r2: 0.084187
- mae: 0.013552
- rmse: 0.020671

Test Metrics:
- r2: -0.003654
- mae: 0.013188
- rmse: 0.019701

In [ ]:
# Full dataset run
print("Rows for training:", len(feat_df))

result = train_and_tune(feat_df, test_size=0.2, fast=False)

print("\nBest Params:")
for k, v in result.best_params.items():
    print(f"- {k}: {v}")

print("\nTrain Metrics:")
for k, v in result.metrics_train.items():
    print(f"- {k}: {v:.6f}")

print("\nTest Metrics:")
for k, v in result.metrics_test.items():
    print(f"- {k}: {v:.6f}")

Rows for training: 30488
n_iterations: 7
n_required_iterations: 7
n_possible_iterations: 7
min_resources_: 33
max_resources_: 24390
aggressive_elimination: False
factor: 3
----------
iter: 0
n_candidates: 729
n_resources: 33
Fitting 3 folds for each of 729 candidates, totalling 2187 fits
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=2, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=50, model__min_samples_leaf=4, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300; total time=   0.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=2, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=200; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=   0.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=   0.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=5, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=100; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=200; total time=   0.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=   0.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=   0.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=1, model__min_samples_split=10, model__n_estimators=300; total time=   0.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__max_leaf_nodes=200, model__min_samples_leaf=2, model__min_samples_split=2, model__n_estimators=100; total time=   0.0s

## Baseline Model Comparison

To strengthen model selection evidence, I also tested a simple **Linear Regression** baseline on the same chronological split.

This helps demonstrate that model choice was considered rather than assumed, and provides a basic point of comparison against the tuned RandomForestRegressor.

In [ ]:
print("\n--- Linear Regression baseline ---")

df = feat_df.dropna(
    subset=FEATURE_COLS_NUM + FEATURE_COLS_CAT + [TARGET_COL]
).copy()
df = df.sort_values(["Date", "Ticker"]).reset_index(drop=True)

train_df, test_df = time_split(df)

X_train = train_df[FEATURE_COLS_NUM]
y_train = train_df[TARGET_COL]

X_test = test_df[FEATURE_COLS_NUM]
y_test = test_df[TARGET_COL]

lr = LinearRegression()
lr.fit(X_train, y_train)

pred = lr.predict(X_test)

print("Linear Regression Test R²:", r2_score(y_test, pred))

--- Linear Regression baseline ---
Linear Regression Test R²: -0.004246524532374174

In [ ]:
print("\n--- Dummy Regressor baseline ---")

dummy = DummyRegressor(strategy="mean")
dummy.fit(X_train, y_train)

pred_dummy = dummy.predict(X_test)

print("Dummy Test R²:", r2_score(y_test, pred_dummy))

--- Dummy Regressor baseline ---
Dummy Test R²: -3.975085878260565e-05

## Hyperparameter Optimisation Rationale

I’m using a **RandomForestRegressor** as a solid baseline model for tabular financial features.

Hyperparameter tuning is implemented using **GridSearchCV** with a **TimeSeriesSplit**
cross-validation strategy so that validation respects chronological order
(preventing future data leakage into past training folds).

### Two run modes
- **fast=True**: small grid used for quick validation while building the notebook.
- **fast=False**: full grid used for the final optimisation run (meets the ≥6 hyperparameters with ≥3 values each requirement).

### Hyperparameters tuned (full grid)
- `n_estimators`: number of trees (affects bias/variance trade-off).
- `max_depth`: controls model complexity to reduce overfitting.
- `min_samples_split`: minimum samples required to split a node.
- `min_samples_leaf`: minimum samples required in a leaf node.
- `max_features`: number of features considered per split (tree diversity).
- `max_leaf_nodes`: upper bound on tree size (regularisation).

The grid spans conservative (more regularisation) and more flexible (less regularisation) 
configurations, allowing the model to be selected based on time-aware validation performance.

In [14]:
model_filename = f"stock_forecast_model_{VERSION}.pkl"
model_path = save_model(result.model, MODELS_DIR, model_filename)

print("Saved model to:", model_path)

Saved model to: C:\Users\Louis\Documents\vscode-projects\stockmetrics\models\stock_forecast_model_v2.pkl

In [ ]:
report = {
    "version": VERSION,
    "dataset": f"data/processed/{VERSION}/features_{VERSION}_latest.csv",
    "task": (
        "Regression: predict next-day return "
        "(target_next_day_return = return_1d.shift(-1))"
    ),
    "algorithm": "RandomForestRegressor",
    "best_params": result.best_params,
    "metrics_train": result.metrics_train,
    "metrics_test": result.metrics_test,
}

report_path = REPORTS_DIR / f"model_training_report_{VERSION}.json"
with open(report_path, "w", encoding="utf-8") as f:
    json.dump(report, f, indent=2)

print("Saved training report to:", report_path)

Saved training report to: C:\Users\Louis\Documents\vscode-projects\stockmetrics\outputs\v2\reports\model_training_report_v2.json

## Interpretation (What this means for StockMetrics)

The final model achieved a **positive Test R²**, which means it captured a **small generalisable signal** on unseen data.

This means the model was **successful against the business case**, because the project defined success as:

- **Test R² > 0**

However, the predictive strength remains **weak**, so the model should still be interpreted cautiously.

What this means in practice:

- the engineered features contained some short-horizon predictive information
- the signal is still small relative to the noise in daily stock returns
- the model is useful as an educational example, not as a dependable trading tool

For this reason, StockMetrics still presents long-horizon outcomes as **scenario ranges**
(optimistic / realistic / pessimistic), not guaranteed outcomes.

The dashboard therefore communicates both points clearly:
- the business case was met
- uncertainty remains high

In [ ]:
# Extract feature importance from the fitted Random Forest inside the pipeline
try:
    model = result.model.named_steps["model"]
    preprocess = result.model.named_steps["preprocess"]

    # Get feature names after preprocessing
    num_features = preprocess.transformers_[0][2]  # FEATURE_COLS_NUM
    cat_ohe = preprocess.transformers_[1][1].named_steps["onehot"]
    cat_features = cat_ohe.get_feature_names_out(
        preprocess.transformers_[1][2]
    )

    feature_names = list(num_features) + list(cat_features)
    importances = model.feature_importances_

    fi = pd.DataFrame(
        {"feature": feature_names, "importance": importances}
    )
    fi = fi.sort_values("importance", ascending=False).head(15)

    display(fi)
except Exception as e:
    print("Could not extract feature importance:", e)

              feature  importance
7        lag_return_1    0.171633
8        lag_return_5    0.122169
2             mom_30d    0.115727
5   mean_reversion_5d    0.107892
0             vol_30d    0.093446
1             vol_90d    0.085821
3             mom_90d    0.079033
9       lag_return_21    0.078925
4          zscore_30d    0.071197
6            drawdown    0.060137
16        Ticker_TSLA    0.008318
15        Ticker_NVDA    0.002629
13        Ticker_META    0.001319
14        Ticker_MSFT    0.000743
11        Ticker_AMZN    0.000427